name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --configuration Release --no-restore 
    - name: Test
      run: |
        cd src
        dotnet test --no-restore --verbosity normal
    - name: Changelog checker
      uses: Zomzog/changelog-checker@v1.0.0
      with:
        # Changelog fileName
        fileName: CHANGELOG.adoc
